language: node_js
node_js:
  - 0.6
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "DISPLAY=:99.0 phantomjs --local-to-remote-url-access=yes test/run-qunit.js file://$PWD/test/test.html"
